name: cd
on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    strategy:
      matrix:
        env: [ develop, main]
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    if: github.ref == 'refs/heads/${{ matrix.env}}'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENVIRONMENT: ${{ matrix.env }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install

      - name: Synth stack
        run: npm run cdk synth


      - name: Deploy stack
        run: npm run deploy:cd